/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.drinks;

import java.awt.CardLayout;

/**
 *
 * @author MacaZekoMiš
 */
public class DrinksPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrinksPanel
     */
    
    private CardLayout c2 = new CardLayout();
    public DrinksPanel(String Named) {
        initComponents();
        CardLayout c2 = (CardLayout)jbtpas.getLayout();
        c2.show (jbtpas, Named);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtpas = new keeptoo.KGradientPanel();
        MainPanel = new keeptoo.KGradientPanel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnDodajNovi1 = new javax.swing.JButton();
        btnDodajNovi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jbtpas.setLayout(new java.awt.CardLayout());

        MainPanel.setkEndColor(new java.awt.Color(204, 204, 255));
        MainPanel.setkStartColor(new java.awt.Color(153, 153, 255));

        jButton2.setText("nazad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Beverage");

        btnDodajNovi1.setBackground(new java.awt.Color(0, 0, 0));
        btnDodajNovi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Beer_Glass_52px.png"))); // NOI18N
        btnDodajNovi1.setFocusable(false);
        btnDodajNovi1.setOpaque(false);
        btnDodajNovi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNovi1ActionPerformed(evt);
            }
        });

        btnDodajNovi.setBackground(new java.awt.Color(0, 0, 0));
        btnDodajNovi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Coffee_52px.png"))); // NOI18N
        btnDodajNovi.setFocusable(false);
        btnDodajNovi.setOpaque(false);
        btnDodajNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNoviActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Coffe");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel6)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(btnDodajNovi1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajNovi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDodajNovi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDodajNovi1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jbtpas.add(MainPanel, "drinks");

        add(jbtpas, "jbtpas");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDodajNovi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNovi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDodajNovi1ActionPerformed

    private void btnDodajNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNoviActionPerformed

    }//GEN-LAST:event_btnDodajNoviActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel MainPanel;
    private javax.swing.JButton btnDodajNovi;
    private javax.swing.JButton btnDodajNovi1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private keeptoo.KGradientPanel jbtpas;
    // End of variables declaration//GEN-END:variables
}
